export enum PaymentState {
  IDLE = 'IDLE',
  CREATING_ORDER = 'CREATING_ORDER',
  OPENING_CHECKOUT = 'OPENING_CHECKOUT',
  VERIFYING_PAYMENT = 'VERIFYING_PAYMENT',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
