export enum PlanType {
  DP_STARTER = 'DP_STARTER',
  DP_DESIGNER = 'DP_DESIGNER',
  DP_STUDIO = 'DP_STUDIO',
  DP_STARTER_YEARLY = 'DP_STARTER_YEARLY',
  DP_DESIGNER_YEARLY = 'DP_DESIGNER_YEARLY',
  DP_STUDIO_YEARLY = 'DP_STUDIO_YEARLY',
  DP_TOPUP_SMALL = 'DP_TOPUP_SMALL',
  DP_TOPUP_MEDIUM = 'DP_TOPUP_MEDIUM',
  DP_TOPUP_LARGE = 'DP_TOPUP_LARGE',
}
