import { Component, OnInit } from '@angular/core';
import { DesignService } from '../services/design.service';
import { BreadcrumbService } from '../services/breadcrumb.service';
import { NavigationStart, Router } from '@angular/router';
import { CheckedAttributesService } from '../generate/services/checked-attributes.service';
import { UserService } from '../services/user.service';
import { HttpErrorResponse } from '@angular/common/http';
import { HeaderComponent } from '../header/header.component';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { ToastrService } from 'ngx-toastr';
import { CategoryService } from '../generate/services/category.service';
import { filter, Subscription } from 'rxjs';
import { ErrorService } from '../services/error.service';

@Component({
  standalone: true,
  selector: 'app-design',
  templateUrl: './design.component.html',
  styleUrls: ['./design.component.css'],
  imports: [HeaderComponent, CommonModule, LucideAngularModule],
})
export class DesignComponent implements OnInit {
  design!: string;
  showRegenerateButton: boolean = false;

  private navigationSubscription!: Subscription;

  constructor(
    private designService: DesignService,
    private userService: UserService,
    private breadcrumbService: BreadcrumbService,
    private categoryService: CategoryService,
    private checkAttributeService: CheckedAttributesService,
    private errorService: ErrorService,
    private router: Router,
    private toastr: ToastrService,
  ) {}

  ngOnInit(): void {
    this.getDesign();
    this.onBackButton();
  }

  getDesign() {
    if (this.designService.designUrl.value === '') {
      this.generateDesign();
    } else {
      this.design = this.designService.designUrl.value;
    }
  }

  generateDesign() {
    this.designService.designSubject
      .pipe(filter(Boolean))
      .subscribe((result) => {
        this.showRegenerateButton = result.designType === 'TEXT';
        this.design = result.url;
        this.designService.setDesignId(result.designId);
        this.userService.updateUserDetails();
        this.toastr.success(result.message);
      });
  }

  regenerate() {
    const designId = this.designService.getDesignId();
    if (designId) {
      this.designService.regenerateDesign(designId).subscribe({
        next: (result) => {
          if (result.status === 'Success') {
            this.design = result.url;
            this.userService.updateUserDetails();
          }
        },
        error: (err: HttpErrorResponse) => {
          if (err.error?.status === 'BAD_REQUEST') {
            this.toastr.error(
              err.error?.message || 'Something went wrong. Please try again.',
            );
          } else {
            this.errorService.errorSubject.next(err.error?.status);
            this.router.navigate(['error']);
          }
        },
      });
    } else {
      this.toastr.error('Something went wrong. Please start again.');
      this.router.navigate(['mode']);
    }
  }

  openMode() {
    this.emptyData();
    this.router.navigate(['mode']);
  }

  editDesign() {
    this.designService.designUrl.next(this.design);
    this.router.navigate(['edit']);
  }

  downloadDesign() {
    if (!this.design) {
      this.toastr.error('No design available to download');
      return;
    }
    (async () => {
      try {
        const res = await fetch(this.design);
        if (!res.ok) throw new Error('Network response was not ok');
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'depanoai-design.png';
        document.body.appendChild(a);
        a.click();
        a.remove();
        // revoke after a short delay to ensure download started
        setTimeout(() => URL.revokeObjectURL(url), 1000);
      } catch (err) {
        this.toastr.error('Failed to download design');
      }
    })();
  }

  async shareDesign() {
    if (!this.design) {
      this.toastr.error('No design available to share');
      return;
    }
    // Try Web Share API first
    try {
      if ((navigator as any).share) {
        await (navigator as any).share({
          title: 'My DepanoAI Design',
          text: 'Check out this design generated by Depano AI',
          url: this.design,
        });
        return;
      }

      // Fallback: copy URL to clipboard
      if ((navigator as any).clipboard) {
        await (navigator as any).clipboard.writeText(this.design);
        this.toastr.success('Design link copied to clipboard');
        return;
      }

      this.toastr.info('Sharing not supported in this browser');
    } catch (err) {
      this.toastr.error('Failed to share design');
    }
  }

  emptyData() {
    this.designService.clearDesignData();
    this.categoryService.deleteCategories();
    this.breadcrumbService.emptyBreadcrumbList();
    this.checkAttributeService.emptyCheckedAttributesList();
  }

  onBackButton() {
    this.navigationSubscription = this.router.events.subscribe((event) => {
      if (event instanceof NavigationStart) {
        if (event.navigationTrigger === 'popstate') {
          this.router.navigate(['/home']);
        }
      }
    });
  }

  ngOnDestroy() {
    this.navigationSubscription.unsubscribe();
  }
}
