import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { provideRouter } from '@angular/router';
import { routes } from './app/app.routes';
import { importProvidersFrom } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {
  HTTP_INTERCEPTORS,
  HttpClientModule,
  provideHttpClient,
} from '@angular/common/http';
import { NgxUiLoaderHttpModule, NgxUiLoaderModule } from 'ngx-ui-loader';
import { ToastrModule } from 'ngx-toastr';
import { AuthInterceptor } from './app/auth/services/auth.interceptor';
import {
  ArrowRight,
  BadgeQuestionMark,
  BookOpen,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  CircleUserRound,
  Clock,
  Download,
  Facebook,
  FileImage,
  FileText,
  Globe,
  Heart,
  HelpCircle,
  Instagram,
  Linkedin,
  LogIn,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  Palette,
  Phone,
  Plus,
  Repeat,
  Repeat2,
  RotateCcw,
  Scissors,
  Share2,
  Shield,
  Shirt,
  Smartphone,
  Sparkles,
  SquarePen,
  Twitter,
  Upload,
  User,
  UserPlus,
  Users,
  Wand,
  Wand2,
  WandSparkles,
  X,
  Youtube,
  Zap,
} from 'lucide-angular';

bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient(),
    provideRouter(routes),
    importProvidersFrom(
      BrowserAnimationsModule,
      HttpClientModule,
      NgxUiLoaderModule,
      ToastrModule.forRoot(),
      NgxUiLoaderHttpModule.forRoot({ showForeground: true }),
      LucideAngularModule.pick({
        Sparkles,
        Phone,
        MapPin,
        Heart,
        Instagram,
        Twitter,
        Facebook,
        Linkedin,
        Youtube,
        Users,
        Palette,
        Wand2,
        Camera,
        User,
        Shield,
        FileText,
        HelpCircle,
        Globe,
        Clock,
        LogIn,
        UserPlus,
        BookOpen,
        Scissors,
        Shirt,
        ChevronLeft,
        ChevronRight,
        WandSparkles,
        BadgeQuestionMark,
        Mail,
        Smartphone,
        ArrowRight,
        Upload,
        CircleCheckBig,
        Wand,
        FileImage,
        Zap,
        Share2,
        Repeat,
        ChevronDown,
        Plus,
        X,
        CircleUserRound,
        LogOut,
        Repeat2,
        SquarePen,
        RotateCcw,
        Download,
      }),
    ),
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
  ],
});
